Args = --no-fallback \
       --enable-url-protocols=http,https \
       --enable-preview \
       --initialize-at-build-time=org.slf4j.LoggerFactory \
       --initialize-at-run-time=io.github.mymonstercat.ocr.InferenceEngine,java.awt.Toolkit \
       -H:+ReportExceptionStackTraces \
       --allow-incomplete-classpath \
       -H:Class=com.ocr.nospring.NativeCli \
       -H:IncludeResources=.*\\.json$,.*\\.properties$,.*\\.xml$,.*\\.onnx$,.*\\.dll$,.*\\.so$,.*\\.dylib$
